language: node_js
node_js:
  - "8"
install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm test
    - stage: publish_contracts
      script: npm run pact:publish:dev

stages:
  - name: test
  - name: publish_contracts
    if: branch = master AND type != pull_request